# Generated by Django 2.0.5 on 2018-05-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmjb', '0002_job_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
